[colors.bright]
black = "#333333"
blue = "#888888"
cyan = "#aaaaaa"
green = "#d0dfee"
magenta = "#999999"
red = "#5f8787"
white = "#c1c1c1"
yellow = "#5f81a5"

[colors.normal]
black = "#000000"
blue = "#888888"
cyan = "#aaaaaa"
green = "#d0dfee"
magenta = "#999999"
red = "#5f8787"
white = "#c1c1c1"
yellow = "#5f81a5"

[colors.primary]
background = "#000000"
foreground = "#c1c1c1"
